<?php
    $templateName = $template->getName();
    $templateName = $templateName ? $templateName : 'Template';

    $badges = [];
    if ($template->getIsSystem()) {
        $badges[] = ['label' => 'System Template (Read-Only)', 'icon' => 'fa-lock', 'class' => 'badge-system'];
    }

    $rightContent = '';
    if (!$template->getIsSystem()) {
        $rightContent .= '<div class="save-indicator saved" style="display: flex;"><i class="fas fa-check-circle"></i><span>Saved</span></div>';
        $rightContent .= '<button class="btn btn-icon btn-outline-warning" id="edit-template-details-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Edit Details"><i class="fas fa-pencil"></i></button>';
    }
    $rightContent .= '<a href="?urlq=dashboard/template/preview/' . $template->getId() . '" class="btn btn-icon btn-outline-primary btn-view-mode" data-bs-toggle="tooltip" data-bs-placement="bottom" title="View Mode"><i class="fas fa-eye"></i></a>';
    if (!$template->getIsSystem()) {
        $rightContent .= '<div class="form-check form-switch text-switch text-switch-purple"><input class="form-check-input" type="checkbox" role="switch" id="toggle-layout-edit-switch"><div class="text-switch-track"><span class="text-switch-knob"></span><span class="text-switch-label label-text">Tweak</span></div></div>';
    }

    echo Utility::renderPageHeader([
        'title' => $templateName,
        'backUrl' => '?urlq=dashboard/templates',
        'backLabel' => 'Templates',
        'badges' => $badges,
        'rightContent' => $rightContent
    ]);
    ?>

    <div id="dashboard-builder"
        class="dashboard-builder"
        data-mode="template"
        data-template-id="<?php echo $template->getId(); ?>"
        data-is-system="<?php echo $template->getIsSystem() ? '1' : '0'; ?>">

        <div class="builder-body">
            <div class="builder-main">
                <div class="grid-editor">
                    <div class="dashboard-sections">
                        <!-- Loader will be added dynamically by JavaScript -->
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Add Section Modal -->
    <div id="add-section-modal" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-xl modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-title-wrapper">
                        <h5 class="modal-title">Add New Section</h5>
                        <span class="modal-subtitle text-muted">Choose empty columns or select from templates</span>
                    </div>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <!-- Empty Columns Option - buttons generated dynamically by JS based on GRID_CONFIG.MAX_COLUMNS -->
                    <div class="add-section-empty-columns mb-4">
                        <div class="d-flex align-items-center gap-3">
                            <label class="form-label mb-0 fw-semibold">Empty Columns:</label>
                            <div class="d-flex gap-2">
                                <!-- Buttons will be generated by JavaScript -->
                            </div>
                        </div>
                    </div>
                    <hr class="mb-4">
                    <!-- Template List -->
                    <div id="add-section-template-list">
                        <div class="loader">
                            <i class="fas fa-spinner fa-spin loader-spinner"></i>
                            <span class="loader-text">Loading templates...</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Edit Template Details Modal -->
    <div id="edit-template-details-modal" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit Template Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="edit-template-name" class="form-label">Template Name *</label>
                        <?php $name = $template->getName(); ?>
                        <input type="text"
                            class="form-control"
                            id="edit-template-name"
                            value="<?php echo htmlspecialchars($name ? $name : ''); ?>"
                            required>
                        <div class="invalid-feedback">Template name is required</div>
                    </div>
                    <div class="mb-3">
                        <label for="edit-template-description" class="form-label">Description</label>
                        <?php $desc = $template->getDescription(); ?>
                        <textarea class="form-control"
                            id="edit-template-description"
                            rows="3"><?php echo htmlspecialchars($desc ? $desc : ''); ?></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="edit-template-category" class="form-label">Category</label>
                        <select class="form-select select-with-create" id="edit-template-category">
                            <option value="">None (Uncategorized)</option>
                            <?php foreach ($categories as $category): ?>
                            <option value="<?php echo $category->getId(); ?>"
                                    <?php echo ($template->getDtcid() == $category->getId()) ? 'selected' : ''; ?>>
                                <?php echo htmlspecialchars($category->getName()); ?>
                            </option>
                            <?php endforeach; ?>
                            <option value="__new__" class="option-create-new">+ Create New Category</option>
                        </select>
                    </div>

                    <!-- New Category Fields (hidden by default) -->
                    <div id="new-category-fields" class="new-category-fields" style="display: none;">
                        <div class="mb-3">
                            <label for="new-category-name" class="form-label">Category Name *</label>
                            <input type="text"
                                   class="form-control"
                                   id="new-category-name"
                                   placeholder="Enter category name">
                            <div class="invalid-feedback">Category name is required</div>
                        </div>
                        <div class="mb-3">
                            <label for="new-category-description" class="form-label">Category Description</label>
                            <textarea class="form-control"
                                      id="new-category-description"
                                      rows="2"
                                      placeholder="Enter category description (optional)"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-sm btn-primary" id="save-template-details-btn">Save Changes</button>
                </div>
            </div>
        </div>
    </div>

